on:
  push:
    branches:
      - master
  schedule:
    - cron: '38 6 * * 6'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    name: A job to update Readme
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Run script to fetch RSS and update readme
        uses: ./

      - name: Setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit and push
        run: |
          # Stage the file, commit and push
          git add README.md
          git commit -m "updated blog posts in Readme.md"
          git push origin master
